### PR TITLE
2019.3.9 broke AddFileToBuild so moved to AddFileToBuildSection

### LINKED ISSUE #287: Exception "NotificationService.h" error while building for iOS
Since I started to use Unity 2019.3.9 I had to upgrade Onesignal SDK. When I build the XCode project, I get the exception error below and I can't use Onesignal on Xcode (11.3.1). I can't find the source of the problem, so I ask here for help please. I'm using the lastest Google Analytics SDK and I already tested both successfully on Android.

```
`Exception: The given path OneSignalNotificationServiceExtension/NotificationService.h does not refer to a file in a known build section
UnityEditor.iOS.Xcode.PBXProjectData.BuildSectionAny (UnityEditor.iOS.Xcode.PBX.PBXNativeTargetData target, System.String path, System.Boolean isFolderRef) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProjectData.cs:250)
UnityEditor.iOS.Xcode.PBXProject.BuildSectionAny (UnityEditor.iOS.Xcode.PBX.PBXNativeTargetData target, System.String path, System.Boolean isFolderRef) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:86)
UnityEditor.iOS.Xcode.PBXProject.AddBuildFileImpl (System.String targetGuid, System.String fileGuid, System.Boolean weak, System.String compileFlags) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:266)
UnityEditor.iOS.Xcode.PBXProject.AddFileToBuild (System.String targetGuid, System.String fileGuid) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:280)
BuildPostProcessor.AddNotificationServiceExtension (UnityEditor.iOS.Xcode.PBXProject project, System.String path) (at Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs:235)
BuildPostProcessor.OnPostProcessBuild (UnityEditor.BuildTarget target, System.String path) (at Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs:134)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:177)
UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass17_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:433)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:391)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)`
```

### PR DESCRIPTION
**Pull request by jkasten2**
Test on Unity 2019.3.10 and 2017.4.39 on Windows 10. Copied xcode project to macOS 10.15.3 and built with Xcode 11.4 successfully.

* Fixes #287

### CODE REVIEW

File: OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs [hunk 1]
```diff
@@ -231,12 +232,10 @@ private static void AddNotificationServiceExtension(PBXProject project, string p
...
          );
 
-         var sourceDestination = extensionTargetName + "/NotificationService";
-         project.AddFileToBuild(extensionGUID, project.AddFile(sourceDestination + ".h", sourceDestination + ".h", PBXSourceTree.Source));
-         project.AddFileToBuild(extensionGUID, project.AddFile(sourceDestination + ".m", sourceDestination + ".m", PBXSourceTree.Source));
+         AddNotificationServiceSourceFilesToTarget(project, extensionGUID, path);
 
-         foreach(var framework in FRAMEWORKS_TO_ADD) {
-            project.AddFrameworkToProject(extensionGUID, framework, true);
+            foreach(var framework in FRAMEWORKS_TO_ADD) {
```
Comment (mikechoch) [inline OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs:237]: fix this indent

Comment (jkasten2) [reply OneSignalExample/Assets/OneSignal/Editor/PostProcessBuildPlayer_iOS.cs]: Fixed!
